/** Generated by scripts/evaluate_v6.js. */
export const V6_POLICY = Object.freeze({
  "kind": "combo",
  "priorStrength": 50,
  "patternWeight": 0,
  "stateWeight": 0,
  "evidenceId": "v6-combo-baseline-2026-08-29"
});
